#!/usr/bin/env php
<?php

// Set to run indefinitely if needed.
set_time_limit(0);

// Optional. It’s better to do it in the php.ini file.
date_default_timezone_set('Europe/London'); 

// Include the composer autoloader.
require_once __DIR__ . '/../vendor/autoload.php'; 

// Import the Symfony Console Application.
use Symfony\Component\Console\Application; 

$app = new Application();
$app->run();